apiVersion: v1
kind: Service
metadata:
  name: complete-devops-pipeline
spec:
  selector:
    app: complete-devops-pipeline
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
